### ISSUE TITLE
Formularios

### ISSUE THREAD

**Issue by llinares19462** [llinares19462/practica_dwec_gestor_presupuesto#11]
Hola @pedroprieto.
Estoy realizando la parte de formulario, y tengo unas dudas.
- He decidido colocar un div en el html para que se coloque ahí el formulario que se cree. ¿Es correcto o debo hacerlo en otro lugar?
- En la parte del formulario para crear un nuevo gasto, soy incapaz de pasarle al botón enviar los datos que se introducen. Lo he probado de diferentes formas (tomando como ejemplo lo que hiciste al principio de la tutoría del lunes). También le he hachado un vistazo a los apuntes, pero no he encontrado la forma de hacerlo. ¿Me puedes dar alguna orientación?.

Muchas gracias. Un saludo.

**Comment by pedroprieto** [comment]
Buenas,

Puedes hacerlo sin problema. Creo que los tests se lo tragarán...

Con respecto a la segunda pregunta, para crear un nuevo gasto no tienes que pasar nada. Tienes que acceder a los campos del formulario y recoger los datos de ahí. Una vez lo tengas tienes que crear un nuevo gasto (`new CrearGasto(DATOS)`) y llamar a `anyadirGasto` para guardarlo.

Un saludo!

**Comment by llinares19462** [comment]
Hola @pedroprieto.

Creo que no me he explicado bien en la segunda pregunta.
El problema que tengo es que no se como "recoger" el valor introducido en los diferentes inputs. El hecho de hacerlo así de momento es tan solo para comprobar que se como referirme a ellos (es tan solo a efectos de prueba, como hiciste en la tutoría pasando un texto como gasto para comprobar que el botón funcionaba y que se pasaba el texto correspondiente). 

Una vez que sepa exactamente como obtener el valor introducido, tengo claro que ahí se ha de crear el objeto gasto con los diferentes valores y pasarlo al botón de enviar para que ejecute anyadirGasto para que lo añada a los otros.

Esta linea es la que yo he construido (puedes ver otras pruebas que he hecho), pero el resultado es infructuoso.
https://github.com/llinares19462/practica_dwec_gestor_presupuesto/blob/0ac8307b880e101764fd2b85f6e4c0bf789ea487/js/gestionPresupuestoWeb.js#L277

Lo que tampoco tengo claro es si esta "recogida" de datos se tiene que hacer antes o despues de haber pintado el formulario en la web.

Muchas gracias. Un saludo.

**Comment by pedroprieto** [comment]
Buenas,

He ido a mirar el último comentario que me has puesto pero lo has borrado. ¿Entiendo que lo has solucionado?

Saludos!

**Comment by llinares19462** [comment]
Buenas @pedroprieto.
Efectivamente anoche despues de escribir el comentario, descubrí como hacerlo, por lo que lo borré.
Ahora ya funciona correctamente, pero no cierra el formulario despues de haber "enviado" el nuevo gasto. He probado con la misma estrategia que el botón cerrar, pero me dá error (me dice que no existe el form).

Aquí puedes ver las pruebas que he hecho. Es a partir de esa linea de código, no se como poner varias lineas a la vez ;( 
https://github.com/llinares19462/practica_dwec_gestor_presupuesto/blob/c36eeb0cf6eb65f7187b02714ec2116a46f4fd36/js/gestionPresupuestoWeb.js#L320

Me puedes dar alguna indicación. Muchas gracias.

**Comment by llinares19462** [comment]
Hola nuevamente....... ya he solucionado lo del botón, ahora ya cierra correctamente el formulario tras añadir el nuevo gasto.
Tambien he modificado el lugar donde debe salir el formulario
https://github.com/llinares19462/practica_dwec_gestor_presupuesto/blob/89ce863fcb6dbe1513e98a572fa26d72a9137d64/js/gestionPresupuestoWeb.js#L286

Pero aún así, no pasa el test 
 1) Formularios
       Función nuevoGastoWebFormulario y botón anyadirgasto-formulario:
     AssertionError: Timed out retrying after 4000ms: Se debe mostrar la cantidad correspondiente a los gastos totales mediante la función 'calcularTotalGastos': expected '<div#gastos-totales>' to contain '563'
      at Context.eval (http://localhost:41205/__cypress/tests?p=test/06_testFormularios.js:119:131)

¿Me puedes dar alguna indicación?
Muchas gracias. Un saludo.

**Comment by llinares19462** [comment]
Es que las prisas.........
Solucionado.  Muchas gracias.
