### ISSUE TITLE
Formulario editar gasto

### ISSUE THREAD

**Issue by llinares19462** [llinares19462/practica_dwec_gestor_presupuesto#12]
Buenas tardes/noches @pedroprieto.

Estoy con la creación del formulario para editar un gasto, pero me encuentro una dificultad. Nose como pasarle al botón que crea el formulario el lugar donde se debe crear. 

Se que desde este punto que es donde creo el botón, se le debe pasar la información del lugar
https://github.com/llinares19462/practica_dwec_gestor_presupuesto/blob/48f3f2eaf8d908a6c63ef30d257ca1e2ccf001c8/js/gestionPresupuestoWeb.js#L94

para que aquí se agrege el formulario en el gasto correspondiente
https://github.com/llinares19462/practica_dwec_gestor_presupuesto/blob/48f3f2eaf8d908a6c63ef30d257ca1e2ccf001c8/js/gestionPresupuestoWeb.js#L118

¿Me puedes dar alguna indicación?

Muchas gracias. Un saludo.

**Comment by llinares19462** [comment]
De momento solucionado....... pero dejo dejo abierto el issue por si acaso...

**Comment by llinares19462** [comment]
Buenos Dias @pedroprieto.

Estoy todavía con el formulario de editar gasto y tengo algunos problemas/dudas:

- Al abrir el formulario con el gasto a modificar, el formato del mismo, sale muy mal (te puedo pasar captura por email) ¿a que puede ser debido si es el mismo template que el de añadir gasto?.
https://github.com/llinares19462/practica_dwec_gestor_presupuesto/blob/62282828b605bd0f293ed7e948a21e8a4812fa59/js/gestionPresupuestoWeb.js#L110

- En el formulario me aparecen todos los datos del gasto, pero no la fecha. He mirado los apuntes y más weds de información, pero soy incapaz de que lo muestre, ¿me puedes dar alguna indicación?.
https://github.com/llinares19462/practica_dwec_gestor_presupuesto/blob/62282828b605bd0f293ed7e948a21e8a4812fa59/js/gestionPresupuestoWeb.js#L144

- Soy incapaz de realizar la modificación del gasto
https://github.com/llinares19462/practica_dwec_gestor_presupuesto/blob/62282828b605bd0f293ed7e948a21e8a4812fa59/js/gestionPresupuestoWeb.js#L171

Muchas gracias.

**Comment by pedroprieto** [comment]
Buenas,

Creo que con la tutoría de hoy ha quedado aclarado, ¿no?

Saludos!

**Comment by llinares19462** [comment]
Buenas tarde nuevamente @pedroprieto.

Efectivamente, tras la tutoría de esta tarde todo resuelto, ....... pero.........

He estado ahora acabando el código para comprobar que funciona correctamente, pero aunque pasa los test (al menos en local), pero veo un  problema en las etiquetas. Al realizar la actualización de un gasto, y aunque no se modifique nada, se realiza un duplicado de las mismas. He seguido la misma estrategia que la forma de edicior por prompt, pero no veo el porqué.
¿Me puede dar alguna indicación?
Muchas gracias. Un saludo.

**Comment by pedroprieto** [comment]
Buenas,

Lo que ocurre es que te crea una etiqueta con el texto de todas a la vez. El problema está aquí:
https://github.com/llinares19462/practica_dwec_gestor_presupuesto/blob/318643e1f9941baaf24a8f392f0c5030a625a6a1/js/gestionPresupuestoWeb.js#L197

Recuerda que `anyadirEtiquetas` necesita una lista de parámetros. Y tú le estás pasando un array. Ahí está el problema. Pista: https://es.javascript.info/rest-parameters-spread

Saludos!

**Comment by llinares19462** [comment]
Hola @pedroprieto.

Solucionado. Ahora funciona correctamente.

Te hago el pull request.

Muchas gracias.

**Comment by pedroprieto** [comment]
:+1:
