### ISSUE TITLE
Expresiones regulares

### ISSUE THREAD

**Issue by llinares19462** [llinares19462/practica_dwec_gestor_presupuesto#13]
Buenos dias @pedroprieto
Estoy haciendo la práctica de expresiones regulares, y me encuentro con un problema que estoy intentando resolver lo que llevamos de mañana.
En la nueva función que debemos crear para "normalizar" las etiquetas antes del filtrado, no consigo que se realice correctamente. 
Tras revisar los apuntes indicados y haciendo pruebas en la web de regextester, llegué a lo que yo creo que es la expresión a utilizar, pero en el test me continúa dando fallo.
https://github.com/llinares19462/practica_dwec_gestor_presupuesto/blob/c8cd30453f5f5db7d7033d49eafe3f1069485704/js/gestionPresupuesto.js#L477

¿Me puedes dar alguna indicación?
Muchas gracias.

**Comment by llinares19462** [comment]
Hola nuevamente @pedroprieto

A parte del problema anterior, también tengo otra duda/problema.

Estoy haciendo el filtrado de los gastos, pero no logro hacer el borrado de los resultados previos. Lo he intentado mediante 
https://github.com/llinares19462/practica_dwec_gestor_presupuesto/blob/188f61983612812250bce4bb5700e18c075635cb/js/gestionPresupuestoWeb.js#L508
pero me da error.
¿Me puedes dar alguna indicacion?
Muchas gracias. Un saludo.

**Comment by llinares19462** [comment]
Buenas tardes @pedroprieto 
Ya he solucionado la primera duda. Lo he hecho como tu me has indicado y he conseguido que cree el array de etiquetas.

Peeeeero la segunda duda soy incapaz de resolverla. No consigo sobreescribir el contenido del div, siempre me aparecen por duplicado.

**Comment by pedroprieto** [comment]
Chico, si es muy fácil: simplemente localiza el `div` y pon su `innerHTML` igual a una cadena vacía.

**Comment by llinares19462** [comment]
Hola nuevamente @pedroprieto 

He modificado la linea 
https://github.com/llinares19462/practica_dwec_gestor_presupuesto/blob/38eb46238d1f09499f5f5e6e44cd756d0c1c7131/js/gestionPresupuestoWeb.js#L536
a conforme yo creo que debe ser para que "borre" el contenido del div (y lo borra -> lo he comprobado quitand la parte de abajo donde vuelve a pintar el resultado "filtrado"), pero no consigo que realice el filtrado. He seguido la pautas de como debe estar filtrado y creo que es correcto. 
¿Puedes ayudarme a ver donde está mal?, porque por mas que miro creo que es correcto.

Muchas gracias.

**Comment by pedroprieto** [comment]
`filtrarGastos` admite un objeto como parámetro. No le estás pasando un objeto en `cadenaBusqueda`...

**Comment by pedroprieto** [comment]
https://github.com/llinares19462/practica_dwec_gestor_presupuesto/blob/38eb46238d1f09499f5f5e6e44cd756d0c1c7131/js/gestionPresupuestoWeb.js#L537

**Comment by llinares19462** [comment]
Buenos dias @pedroprieto 

Estoy dándole vueltas al problema de generar el objeto para hacer el filtrado.

He modificado esta línea para que me genere un array  a partir del string que obtengo al recoger los datos del formulario para de esa manera hacer el filtrado.
https://github.com/llinares19462/practica_dwec_gestor_presupuesto/blob/3dc9d3a4d7407209a943bbe9d6441bf6877a7af5/js/gestionPresupuestoWeb.js#L550

Llevo ya unos cuantos intentando buscar una solución.

A ver si me puedes echar una mano.

Muchas gracias.

**Comment by pedroprieto** [comment]
Buenas,

Mira cómo creabas el objeto en la práctica anterior:
https://github.com/llinares19462/practica_dwec_gestor_presupuesto/blob/3dc9d3a4d7407209a943bbe9d6441bf6877a7af5/js/generarDatosEstadisticos.js#L39

Tienes que hacer algo parecido. Lo único, los valores de filtrado ya no serán valores literales, sino los valores de los campos de formulario.

Un saludo!

**Comment by llinares19462** [comment]
Buenos dias @pedroprieto 

Estoy dándole vueltas al problema de generar el objeto para hacer el filtrado.

He modificado esta línea para que me genere un array  a partir del string que obtengo al recoger los datos del formulario para de esa manera hacer el filtrado.
https://github.com/llinares19462/practica_dwec_gestor_presupuesto/blob/3dc9d3a4d7407209a943bbe9d6441bf6877a7af5/js/gestionPresupuestoWeb.js#L550

Llevo ya unos cuantos intentando buscar una solución.

A ver si me puedes echar una mano.

Muchas gracias.

**Comment by llinares19462** [comment]
Buenos dias @pedroprieto 

Continuo atascado en el mismo sistio.

He intentado modificar la cadena de búsqueda, par que se adapte al formato que me has indicado (el que utilizamos inicialmente para hacer unos filtrados) pero no encuentro la forma correcta de hacerlo.

https://github.com/llinares19462/practica_dwec_gestor_presupuesto/blob/701e851e0ea1f1ce701a0650bc4434cb55b41587/js/gestionPresupuestoWeb.js#L551

De momento probándolo para realizar un filtrado de valor del gasto.

¿Me puedes dar alguna indicación más?

Muchas gracias.

**Comment by pedroprieto** [comment]
Buenas,

No utilices cadenas de ningún tipo. Simplemente crea un objeto con los parámetros que necesitas. Para cada parámetro le pasas el dato guardado en el campo de formulario correspondiente.

Un saludo!!

**Comment by llinares19462** [comment]
Buenos Dias @pedroprieto 

TAl y como me sugeriste ayer, he modificado el código par que se cree un objeto
https://github.com/llinares19462/practica_dwec_gestor_presupuesto/blob/91b519f7e12fa4533b735745e98520436c17677b/js/gestionPresupuestoWeb.js#L474

Después, segun se haya introducido un valor o no en los diferentes campos de texto, se añade o no al objeto
https://github.com/llinares19462/practica_dwec_gestor_presupuesto/blob/91b519f7e12fa4533b735745e98520436c17677b/js/gestionPresupuestoWeb.js#L477-L539

Pero aún asi y todo no funciona correctamente......

A ver si me puedes indicar algo.

Muchas gracias. Un saludo.

**Comment by pedroprieto** [comment]
Si subes el código puedo verlo...

**Comment by llinares19462** [comment]
Hola @pedroprieto 

El código está subido a github. Los recortes de que te he puesto antes son directamente del código que he modificado.
Esta es la ultima version de mi código.

**Comment by pedroprieto** [comment]
Esto simplemente es hacer:
https://github.com/llinares19462/practica_dwec_gestor_presupuesto/blob/91b519f7e12fa4533b735745e98520436c17677b/js/gestionPresupuestoWeb.js#L474
```js
let busqueda = {};
```

Y esto:
https://github.com/llinares19462/practica_dwec_gestor_presupuesto/blob/91b519f7e12fa4533b735745e98520436c17677b/js/gestionPresupuestoWeb.js#L568
```js
 let resultado = gespres.filtrarGastos(busqueda); 
```

**Comment by llinares19462** [comment]
Hola @pedroprieto 

Muchas gracias por tu ayuda, ya funciona correctamente el filtrado. En local me pasa los test perfectamente.

Pero revisando el funcionamiento del conjunto del programa, me he dado cuenta de un problema. 
Al añadir un nuevo gasto a través del formulario, las etiquetas, las crea como una única, no como varias.
Y si editamos ese nuevo gasto posteriormente y le añadimos nuevas etiquetas, estas si que las separa convenientemente.
El código que utilizo es este
https://github.com/llinares19462/practica_dwec_gestor_presupuesto/blob/b2ea42436b50b3fc70b79e5c7cca5a81b0ed6e11/js/gestionPresupuestoWeb.js#L422-L440

¿Me puede indicar por donde echarle mano para que esto no pase?

Muchas Gracias. Un saludo.

**Comment by pedroprieto** [comment]
Buenas,

Sí, tienes un fallo:
https://github.com/llinares19462/practica_dwec_gestor_presupuesto/blob/b2ea42436b50b3fc70b79e5c7cca5a81b0ed6e11/js/gestionPresupuestoWeb.js#L435
https://github.com/llinares19462/practica_dwec_gestor_presupuesto/blob/b2ea42436b50b3fc70b79e5c7cca5a81b0ed6e11/js/gestionPresupuestoWeb.js#L439

Pasas directamente el contenido del campo, que es una cadena de texto con las etiquetas separadas por comas. Por tanto, se te crea una única etiqueta con dicho texto separado por comas.

Lo que tienes que hacer es:
- Convertir la cadena de texto a un array de elementos
- Pasar el array **como lista de parámetros** a la función `CrearGasto`. Pista: https://es.javascript.info/rest-parameters-spread

Un saludo!

**Comment by llinares19462** [comment]
Solucionado el problema. Muchas gracias por tu ayuda.

**Comment by pedroprieto** [comment]
:+1:
