### ISSUE TITLE
Almacenamiento

### ISSUE THREAD

**Issue by llinares19462** [llinares19462/practica_dwec_gestor_presupuesto#14]
Buenos Dias @pedroprieto.

Estoy desde ayer con la parte de almacenamiento y tengo un pequeño problema......

He creado los eventos para el click de los botones
https://github.com/llinares19462/practica_dwec_gestor_presupuesto/blob/c8525b04386d58455f4e51f75a98665f060c5cc4/js/gestionPresupuestoWeb.js#L624-L630

Y aquí he empezado a crear la funcionalidad asociada a los mismos
https://github.com/llinares19462/practica_dwec_gestor_presupuesto/blob/c8525b04386d58455f4e51f75a98665f060c5cc4/js/gestionPresupuestoWeb.js#L589-L605

Pero resulta que al pulsar los botones, no sucede nada (por eso tengo los console.log para realizar las comprobaciones de cuando se pulsan).

¿Me puedes dar alguna indicación?

Muchas gracias. Un saludo.

**Comment by pedroprieto** [comment]
Buenas,

Efectivamente, no sucede nada porque has utilizado funciones manejadoras de eventos. Pero las has implementado como si fueran **objetos** manejadores de eventos.

Las funciones manejadoras de eventos no tienen que definir `handleEvent`:
https://github.com/llinares19462/practica_dwec_gestor_presupuesto/blob/c8525b04386d58455f4e51f75a98665f060c5cc4/js/gestionPresupuestoWeb.js#L590

Un saludo!

**Comment by llinares19462** [comment]
Hola @pedroprieto.

Solucionado ese tema, ya casi funciona.......

Al recuperar los datos guardados anteriormente

https://github.com/llinares19462/practica_dwec_gestor_presupuesto/blob/0c07db233d15d69188618b4f457d080b8c28e49e/js/gestionPresupuestoWeb.js#L612

los muestra bien en la web, pero hay un problema con las etiquetas, parece que no las crea bien. He revisado en la consola el resultado, y veo que si que se crean los objetos correspondientes, incluidas las etiquetas en array, pero a la hora de borrar alguna de ellas es donde dá el error (esto también hace que no supere el tercer test 8).

A ver si me puede dar alguna indicación.

Muchas gracias.

**Comment by pedroprieto** [comment]
Muy buenas,

Hay dos errores: el primero, el del test, no es por las etiquetas, sino que no controlas el caso particular de que no existan datos guardados. Si la carga de datos es `null` debes crear un array vacío para llamar a `cargarGastos`.

El segundo, el de las etiquetas, se debe a que al cargar los datos solo se recrean los datos del objeto, no la funcionalidad del objeto entera. Por tanto, dichos objetos no tienen acceso a los métodos (`borrarEtiquetas`, etc.). Esto es un fallo mío en el planteamiento de la práctica que os comentaré la semana que viene en tutoría. Puedes despreocuparte :wink: 

Un saludo!!
