### ISSUE TITLE
Funciones asíncronas.

### ISSUE THREAD

**Issue by llinares19462** [llinares19462/practica_dwec_gestor_presupuesto#15]
Buenas @pedroprieto.

Feliz Año Nuevo!!!!!!!!!

Retomando las prácticas donde las dejé el ultimo año, me he encontrado con problemas......... ;)
Al hacer la función que recupera los datos que están en la API externa, he "recreado" la forma en la que tu olo hacías en la última práctica, pero me indica que "await" es un identificador reservado.

https://github.com/llinares19462/practica_dwec_gestor_presupuesto/blob/4f4a9d5c7b26f7aadbef59ceaaf1e9c608f23585/js/gestionPresupuestoWeb.js#L630-L650
¿Me puedes dar alguna indicación?

Mchas gracias, un saludo.

**Comment by llinares19462** [comment]
Hola nuevamente @pedroprieto.

De momento solucionado, habia olvidado ponerlo en una función asíncrona.

Dejo abierto el issue para nuevas dudas.

Muchas gracias.

**Comment by pedroprieto** [comment]
:+1:
