### ISSUE TITLE
Funciones Asincronas _ bis

### ISSUE THREAD

**Issue by llinares19462** [llinares19462/practica_dwec_gestor_presupuesto#16]
Buenas tardes @pedroprieto.

Como te he comentado en la tutoría, te muestro donde me aparece el error al intentar hacer funcionar la aplicación.

https://github.com/llinares19462/practica_dwec_gestor_presupuesto/blob/499bb79f2ab114c68b12e488d61675abc0d90163/js/gestionPresupuestoWeb.js#L641-L665

concretamente en el inspector de firefox, me dice que la variable  "carga_datos_API" no está definida al intentar mostrar lo recuperado desde aws. El usuario que estoy utilizando en "frlc".

P.D. Todavía no está hecha la modificación del código que incluye la "rehidratación" de los datos.

Muchas gracias. Un saludo.

**Comment by pedroprieto** [comment]
Buenas,

¿Por qué creas dos funciones iguales?
https://github.com/llinares19462/practica_dwec_gestor_presupuesto/blob/499bb79f2ab114c68b12e488d61675abc0d90163/js/gestionPresupuestoWeb.js#L641

https://github.com/llinares19462/practica_dwec_gestor_presupuesto/blob/499bb79f2ab114c68b12e488d61675abc0d90163/js/gestionPresupuestoWeb.js#L646

Directamente define la primera como función asíncrona y así puedes poner el código de la segunda dentro de la primera.

Lógicamente esto no funciona:
https://github.com/llinares19462/practica_dwec_gestor_presupuesto/blob/499bb79f2ab114c68b12e488d61675abc0d90163/js/gestionPresupuestoWeb.js#L656

Ya que haces referencia desde fuera de una función a una variable creada dentro de dicha función (`carga_datos_API` está definida aquí):
https://github.com/llinares19462/practica_dwec_gestor_presupuesto/blob/499bb79f2ab114c68b12e488d61675abc0d90163/js/gestionPresupuestoWeb.js#L648

Un saludo!

**Comment by llinares19462** [comment]
Hola @pedroprieto 

Ya he realizado las modificaciones que me has sugerido, y creo que ahora casi funciona. El casi creo que es por que no tengo todavía implementada la "rehidratacion" que comentaste ayer. Voy a realizar esa modificación, a ver si de esa manera saco algo en claro.

Muchas gracias.

**Comment by llinares19462** [comment]
Hola nuevamente @pedroprieto 

Modificado el código de cargargasto y ya no me aparece el error al importar los datos desde la web.

Voy con el código de los siguientes botones.

Muchas gracias.

**Comment by pedroprieto** [comment]
Ánimo pues!! :muscle:
