### ISSUE TITLE
Funciones asíncronas _ boton borrar

### ISSUE THREAD

**Issue by llinares19462** [llinares19462/practica_dwec_gestor_presupuesto#17]
Buenos dias nuevamente @pedroprieto

Estoy con el botón borrar de API, pero tengo una ligera duda con el código.

Tal y como hablamos en la tutoría de ayer, para borrar el gasto, lo hacemos a través del id. 
Al intentar recuperar el id del gasto, con aquellos gastos que vienen de la web, me aparece con undefined, pero con los id que se cargar desde local si que me aparece el id correspondiente.
¿A que puede ser debido?
https://github.com/llinares19462/practica_dwec_gestor_presupuesto/blob/716c318e8b01ac1832a05227b3f1d8862f92baea/js/gestionPresupuestoWeb.js#L665-L686

Muchas gracias.

**Comment by pedroprieto** [comment]
La propiedad es `gastoId`, no `id`. La API crea el campo con el nombre `gastoId`. Fallo mío: perdón por la confusión.
https://github.com/llinares19462/practica_dwec_gestor_presupuesto/blob/716c318e8b01ac1832a05227b3f1d8862f92baea/js/gestionPresupuestoWeb.js#L671

![imagen](https://user-images.githubusercontent.com/7632447/148926270-0c65e297-8cfd-41a7-89a0-26bfa4f7329d.png)

**Comment by llinares19462** [comment]
Solucionado. 
Funciona perfectamente ahora.

Muchas gracias por tu ayuda.
