### ISSUE TITLE
Dudas con funcoin filtrarGastos - Javascript 3

### ISSUE THREAD

**Issue by llinares19462** [llinares19462/practica_dwec_gestor_presupuesto#3]
Buenos días @pedroprieto.
Tal y como te indico en el enunciado estoy teniendo problemas con la funcion filtrarGastos.
Me he vuelto a ver el video de la tutoría, pero aún así y todo tengo dudas.
Por lo que puedo entender esta fución cogerá el array gastos (creado con datos anteriormente) y lo filtrará (mediante if), creando un nuevo array que será el resultado.
He intentado recorrer lo que yo creo que es el array creado, pero a la hora de mostrarlo por pantalla, no me aparece nigún reultado. 
¿Podrías darme alguna indicación?

Muchas gracias. Un saludo.

**Comment by llinares19462** [comment]
filtrarGastos ya funciona correctamente.

**Comment by pedroprieto** [comment]
Bien resuelto, Francisco :clap:
