### ISSUE TITLE
Javascript 3 - filtrarGastos

### ISSUE THREAD

**Issue by llinares19462** [llinares19462/practica_dwec_gestor_presupuesto#4]
Buenos dias @pedroprieto.
Tras la tutoría de ayer, he modificado la función filtrarGastos, para que lo haga con filter y no con el bucle (cmo yo originalmente lo tenía hecho. Pero ahora no consigo que funcione correctamente (y eso que lo he hecho mirando el video).
¿Podrías hecharme una mano?.
Muchas gracias.

**Comment by llinares19462** [comment]
Por lo que he podido ver al poner puntos de interrupción, al entrar en la función, no se le pasan los parámetros de filtrado.

**Comment by llinares19462** [comment]
Solucionado.

**Comment by llinares19462** [comment]
Solucionado.

**Comment by pedroprieto** [comment]
:+1:
