### ISSUE TITLE
Interaccion con  HTML

### ISSUE THREAD

**Issue by llinares19462** [llinares19462/practica_dwec_gestor_presupuesto#5]
Buenos dias nuevamente @pedroprieto.
Ahora estoy intentando hacer los primeros de este punto, pero no consigo que funcione correctamente el primero (que aparezca el presupuesto).
Desde mi lógica (jajajajajajajajajaajja) el código está bien, pero no funciona.
¿Me puedes dar alguna indicación?.
Muchas gracias.

**Comment by pedroprieto** [comment]
Dos fallos:
https://github.com/llinares19462/practica_dwec_gestor_presupuesto/blob/105095c013b886352c055e72e5aed81193e303cf/js/generarDatosEstadisticos.js#L1
https://github.com/llinares19462/practica_dwec_gestor_presupuesto/blob/105095c013b886352c055e72e5aed81193e303cf/js/generarDatosEstadisticos.js#L2

Te falta el `.js` (en ambos imports)

**Comment by llinares19462** [comment]
Hola @pedroprieto.
Ya he añadido la extensión a los archivos. Peeero continua sin funcionar. He probado poniendo el nombre del id de las maneras que se me han acurrido, pero todavía continua sin funcionar.
Ahora lo que me indica es que append no puede añadir un null (cuando le estoy pasando como valor la funcion que muestra el presupuesto actual.).
¿Me puedes dar alguna indicación?
Muchas gracias.

**Comment by llinares19462** [comment]
Hola @pedroprieto .
La primera prueba ya la pasa completamente (al final tenia que hacer todos los de mostrarDatoEnId) para que pasara la prueba.
Voy a continuar con el resto. Cierro este issue y si fuera necesario (que lo será) abro otro.
Muchas gracias. Un saludo.

**Comment by pedroprieto** [comment]
Ok! Bien por haberlo solucionado!! :clap:
