### ISSUE TITLE
Interaccion HTML - agrupar gastos

### ISSUE THREAD

**Issue by llinares19462** [llinares19462/practica_dwec_gestor_presupuesto#6]
Buenos dias @pedroprieto.
He continuado realizando el ejercicio correspondiente a Interaccion con HTML, pero ahora estoy atascado en la parte de afrupar gastos.
Ahora al pasar las pruebas da error (supongo que por haber problemas en la funcion de agrparGastos).
He mirado el enlace que nos das para iterar los resultados que nos devuleve el acumulador.
¿Me puede dar alguna indicación?
Muchas gracias. Un saludo.

**Comment by pedroprieto** [comment]
Buenas,

`agrup` es un objeto. Por tanto, no se puede iterar con `for of`. 
https://github.com/llinares19462/practica_dwec_gestor_presupuesto/blob/1f667324a5ba752ce154c35f7d976e8b21384ee7/js/gestionPresupuestoWeb.js#L82

Sin embargo, puedes utilizar `Object.keys(agrup)` para obtener un array de las propiedades sobre el que iterar, tal como os pongo en el enunciado:
![imagen](https://user-images.githubusercontent.com/7632447/141104123-9172fa7f-97a5-448e-bb48-133390d5cde0.png)

Un saludo!

**Comment by llinares19462** [comment]
Entendido. 
Voy a darle un vistazo a ver si lo soluciono.
Muchas gracias.

**Comment by llinares19462** [comment]
Hola nuevamente @pedroprieto.
Creo que ya he solucionado el problema anterior con tus indicaciones (aunque tambien me he guiado por un ejemplo de MDN Web Docs (Object.entries) -> No se si sirve de esta menera.
El problema es que en la web me aparecen los resultados correctamente, pero en los test no los pasa. En el test

1) Generación de datos estáticos
       Función mostrarGastoWeb - Listado completo de gastos:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `#listado-gastos-completo > div.gasto > div.gasto-etiquetas`, but never found it.
      at Context.eval (http://localhost:33035/__cypress/tests?p=test/04_testInteraccionHTML.js:128:74)

me aparece el error que te pongo. Lo curioso es que antes de hacer el resto de test de agrupacion funcionaba sin problemas.
?Donde está el fallo?, porque los nombres de la etiqueta no se ha cambiado.
Muchas gracias.

**Comment by pedroprieto** [comment]
Te falta una `s`:
https://github.com/llinares19462/practica_dwec_gestor_presupuesto/blob/2831f96ec76beb64c0429c6162e41652fce3dc84/js/gestionPresupuestoWeb.js#L46

Te sobra un `;`:
https://github.com/llinares19462/practica_dwec_gestor_presupuesto/blob/2831f96ec76beb64c0429c6162e41652fce3dc84/js/gestionPresupuestoWeb.js#L73

**Comment by llinares19462** [comment]
Vaya tela la mia...........
Solucionado. También he comprobado el resto y tambien tenía error en "dia", que lo habia puesto sin acento y en "anyo".
Ahora pasa los test prefectamente.
Muchisimas gracias. Un saludo.

**Comment by pedroprieto** [comment]
:+1:
