### ISSUE TITLE
Dudas con comentarios en PR

### ISSUE THREAD

**Issue by llinares19462** [llinares19462/practica_dwec_gestor_presupuesto#7]
Buenos días @pedroprieto.
Estoy modificando el código tal y como me has indicado en los comentarios de la pull request (te escribo esto en este issue, porque no se si poniendo los comentarios en la PR te llegarán).

- Bucle en linea 19 de gestionPresupuestoWeb.js
Hay que poner este bucle en el código de generarDatosEstáticos.js. Entiendo que antes de llamar a la funcion de mostrarGastosWeb, hay que hacer el bucle con el método que nos haga un "filtrado" o agrupación, y el objeto resultante pasarselo a mostrarGastosWeb para que lo pinte.
Voy a hacer pruebas y te comento algo.
P.D. No se por que pero le he puesto generarDatosEstadisticos.js...... (yo y mi dislexia.......)

**Comment by pedroprieto** [comment]
Sí, me llegan, pero mejor por aquí.

Tienes que hacer un bucle para recorrer el array de gastos y para cada elemento llamar a `mostrarGastoWeb` (en singular).

Un saludo!!

**Comment by llinares19462** [comment]
Hola @pedroprieto.
Ya he soluciondao el tema de los bucles. En local me pasa los test.

Ya he hecho push de los cambios.

Muchas gracias.
