### ISSUE TITLE
Eventos: editarGasto

### ISSUE THREAD

**Issue by llinares19462** [llinares19462/practica_dwec_gestor_presupuesto#8]
Buenos dias @pedroprieto.
Estoy con la edicion de gasto de eventos.
Siguiendo tu explicación del lunes pasado he podido empezar a construir la funcion que realiza la modificación del gasto, pero me encuentro con un problema. A la hora de decirle que actualice la descripción (linea 204 de gestionpresupuestoWeb.js), no se como llegar hasta el método que realiza dicha acción dentro del constructor de CrearGasto. Lo he probado de diferentes maneras, pero en ningún caso puedo llegar a el.
¿Me puedes dar alguna orientación?
Muchas gracias.

**Comment by llinares19462** [comment]
He hecho modificaciones en el código, pero soy incapaz de llegar a la función.

**Comment by pedroprieto** [comment]
Creo que ya está resuelto, ¿no? :wink: 

Saludos!!
