### ISSUE TITLE
Eventos - editar gastos

### ISSUE THREAD

**Issue by llinares19462** [llinares19462/practica_dwec_gestor_presupuesto#9]
Buenos Dias @pedroprieto.
Tras la tutoria de ayer, he podido modificar el código de editar gasto, para que realice la función correctamente. Tambien le he añadido funconalidad para que detecte si el nuevo valor está en blanco o si es igual al valor actual del campo.
Pero a la hora de pasar el test me dá fallo. Lo he mirado y en un principio realiza la función bien, pero no se en que punto del código me he equivocado para que no pase el test. 
¿Me puedes hechar una mano?
Muchas gracias. Un saludo.

**Comment by pedroprieto** [comment]
No añades los botones donde toca:
https://github.com/llinares19462/practica_dwec_gestor_presupuesto/blob/e7a45324943bcb3571ba420f1657b7ac1eddcf23/js/gestionPresupuestoWeb.js#L74

Lo tienes que añadir al `div.gasto`, no a `#listado-gastos-completo`.

**Comment by llinares19462** [comment]
Perfecto. Ya he modificado el código y funciona correctamente. También he modificado el código del botón borrar que lo estaba haciendo mientras tanto y tenía el mismo problema.
Muchisimas gracias. Un saludo.
